language: java
install: true
jdk:
  - openjdk11
env:
  global:
    - secure: kUsWxzvKs5C2sykFNxsLYYazygzrNz66MRzswSuqizF84OPiz53/mjN8uuwaO5B9dDNWEyeFeAGYfOmUyRMkm5NeIPPdm6RFQYALsth1od2h6ae+KHw7ZdfYVShYGKYq5KQNUZ8c9R3dsek3UQVT5yWudQQmL0jjxmTyFltMAr4EeQBf1YbgpsSR1dirpXhD8pPQwL2B9xgE8EEWfIde6MRrvU9oM46wd8bCp6ASk5/Tb7ty6ggIBdWkA/Q6o0U2D1eRLtA+pU5c+A/sZqFWs450VbGSXsk83T8SrE2oEV/Slh9VVnsnBZoRlRM2swiL8lTONjCtYPQP80kozWwuAka+YqzREfcJxbLL720LV4nlUnF2I4YA26EoQ3r6HS+0SJbiRYJlNJFjH0pnXBFmWf5yXc3Ho43RRGbi+mPEVZ9nQGjeAcdIq8d1CiWxIfXpKUKlPmypBtubIieO42EcJRqoX6temj8bakZBX/ZL3bvjm7wMhtW1OE8S6INtoQZOT+qkdz4Z7EwfGVi6nBoYb9tS2VPLzratUAKlfFLfz1kz5ijv0P4wR32+jeYRPJEBV82ykPDJ4YAp9cY3R9LJD+n+b8R1QbuMMKzdIfFkHlingLu4pl83nmS0088r5kQs5QjuYrPxREClaopVlDjHWbI+jAQM5AyxciESrkQufUg=
script: chmod +x build.sh && build.sh
